add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold blue"
truncate_to_repo = false

[git_branch]
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 500
style = "dimmed white"

[username]
show_always = true
style_user = "bold cyan"

[hostname]
ssh_only = false
style = "bold cyan"

